server:
  port: 8081

debug: true

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/orkasgb?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: false
  # sa-token配置
  sa-token:
    # token名称 (同时也是cookie名称)
    token-name: orkasgb_satoken
    # token有效期，单位s 默认30天, -1代表永不过期
    timeout: 2592000
    # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
    activity-timeout: -1
    # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
    allow-concurrent-login: false
    # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
    is-share: false
    # token风格
    token-style: uuid

mybatis:
  mapper-locations: classpath:mapper/*.xml

security:
  privateKey: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAMXUo7x3l1sUaoYHTGc0f/95o5YOiVqPCQhZYDU+xI3jsgM2Gvty05ssgHZrM9DA0vEK3F0UGJZium1Qvd0FJQAnkL/hEA4FMqAVfB0D+uRpqyc0IXiDGK7jypz/XKeKSAeSrgWlb2ufjH4HbSDV5je7M6oSv5wzIGd9rInj32dFAgMBAAECgYB3ZekUnJErFV1dWxZPy63dAQssS8W2dFGdSmP4ftOeV2he687JJ/py0x8NWZJCUb5+YHGzc6eLTDb8NxkARlSXfaKlLmzJTD1ETjAgyo70DbFcPBwuTy5KE5FJRYVavUnknQz4iETOox7VJrZGO2AULlUALrZy51QeVjvM7WIAwQJBAOJFtp0Fj7SY6WMn9UW2yCATSiJxtJOgdMLxUJ9cZ1tgaS1Azg94hhnZIrXNnzELtiI+1PT8WlmJ+fBFuwxGsv0CQQDf0laGCAkpeqF7/6Koe37Ndf0cF1SKaM1e+QhLqVCeTLBOFze7rPCTwvc/yhzweOirpz2oEZyapUpKKvjGLivpAkEAhCMyAYC96zlhEgbDtXKIbDLXmEXOrmeFyFIkQuwzb6ldwo+VxnMb3PxwyLrLvFiahGUs9+Rm3uM0kpwmH4UqAQJAOmV7s66nDU50kZCqFMFb3Sl6p3ii0xXy92OMOYlsglDJ8yX1oZ7GihblQZxvHoK9WgPhf1dQ/7w+fMlnbPWg+QJBAMhWM0RJGl8h6ilfZFm8d4aLl2dFkFscOJ9enXwBNd2jp650MUmPx0DdUGcT26gwydTtYtyNBuIRuPdT+gQ1QMw=
  publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDF1KO8d5dbFGqGB0xnNH//eaOWDolajwkIWWA1PsSN47IDNhr7ctObLIB2azPQwNLxCtxdFBiWYrptUL3dBSUAJ5C/4RAOBTKgFXwdA/rkaasnNCF4gxiu48qc/1ynikgHkq4FpW9rn4x+B20g1eY3uzOqEr+cMyBnfayJ499nRQIDAQAB

